### ISSUE TITLE
MacOS version?

### ISSUE THREAD

**Issue by sami-almalki** [MaksBelenko/SimplePDFBuilder#1]
Thanks for the great work.
Do you intend to support MacOS?

**Comment by MaksBelenko** [comment]
> Thanks for the great work.
> Do you intend to support MacOS?

Not atm, i believe it shouldn't be very hard to change it for MacOS i believe as PDFKit is on MacOS 10.14+
I personally don't need it, but pull requests are most welcomed :) 
PS It works with Catalyst absolutely fine if you can use it in your application
